#!/usr/bin/env python3
import hashlib
from base64 import a85encode
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

builder = Gtk.Builder()
builder.add_from_file("/usr/share/passman/window.glade")

class Handler:
    def onDestroy(self, *args):
        Gtk.main_quit()

    def onButtonClicked(self, button):
        website = builder.get_object("website-entry").get_text().encode()
        masterpass = builder.get_object("masterpass-entry").get_text().encode()

        salted = website + masterpass
        hash = hashlib.sha256(salted).digest()
        password = a85encode(hash).decode()

        builder.get_object("finalpass-entry").set_text(password)

builder.connect_signals(Handler())

window = builder.get_object("window")
window.show_all()

Gtk.main()
